using System;

// Перехват всех исключений
// System.Exception

namespace ExceptionSix
{
   internal class Program
   {
      static void Main()
      {
         Console.WriteLine("Hello World!");
      }
   }
}
